### PR TITLE
Added HelloWorld in Java

### PR DESCRIPTION
**Pull request by ConnyHeb**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file is not in a project folder ("Friends", "Games", "BSoD"). This may be intentional, but most likely not. If it is intentional please tag a maintainer.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 2d883fffc69c9900b591d53884d95e3b517cc40e

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 2d883fffc69c9900b591d53884d95e3b517cc40e

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This sort of submission does not have proper checking implemented yet. A maintainer will eventually get to you!

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 2d883fffc69c9900b591d53884d95e3b517cc40e

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file should be called `hello_world.{ext}` where ext is the language extension. Not HelloWorld.java

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 2d883fffc69c9900b591d53884d95e3b517cc40e

**Comment by ConnyHeb** [comment]
I changed the naming now, hope this fits now

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 055a279f1368c65ce631b041dd543bfeefa46cf0

**Pull request closed without merging**
