### PR TITLE
Create AjTafoya.html

### PR DESCRIPTION
**Pull request by AjTafoya**
added new friend to friends folder

### CODE REVIEW

**Comment by AjTafoya** [comment]
Friend

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file does not clearly show a link to your github profile.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 87cb736175bf3378faa41952bd9fadb80e711505

**Comment by AjTafoya** [comment]
Linked

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> c41ac116d48ebfd83c4b18737538021c35d69a99

**Pull request merged**
