### PR TITLE
Happ Hacktoberfest !!

### PR DESCRIPTION
**Pull request by Dr-Wolf-ML**

### CODE REVIEW

**Comment by Dr-Wolf-ML** [comment]
Thanks for the opportunity to be part of this  :)

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 54caf0f20a77b6a698d350d1388a43e2a18e16ce

**Comment by RaidAndFade** [comment]
Do not modify the format of contributors.md

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 54caf0f20a77b6a698d350d1388a43e2a18e16ce

**Pull request closed without merging**
