### PR TITLE
Create hello_world.java

### PR DESCRIPTION
**Pull request by skillinquire**
My submission to Hacktoberfest 2018 challenge.

### CODE REVIEW

**Comment by skillinquire** [comment]
Thank you

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file is not in a project folder ("Friends", "Games", "BSoD"). This may be intentional, but most likely not. If it is intentional please tag a maintainer.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> f04367dec3bb4960a4ddbd96998510bb182cc647

**Comment by skillinquire** [comment]
No I intend to have this under HelloWorld..

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your submission does not follow the format, Make sure to follow the readme!
With input `88XY81`:
You responded with: ```hello_world.java:1: error: illegal character: '#'
# By skillinquire - https://github.com/skillinquire
^
hello_world.java:1: error: class, interface, or enum expected
# By skillinquire - https://github.com/skillinquire
     ^
2 errors```
 while the expected result was: 
```Enter your name: 
Hello 88XY81!
```

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> f04367dec3bb4960a4ddbd96998510bb182cc647

**Comment by skillinquire** [comment]
Updated code

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your PR looks like an ORPHAN (you deleted the fork). This cannot be automatically checked. Please close this PR and create a new one without removing the fork.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 9a198d83880fea8f4a6d86e836deff86e9428d04

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 9a198d83880fea8f4a6d86e836deff86e9428d04

**Pull request closed without merging**
