### PR TITLE
Added me as contributor

### PR DESCRIPTION
**Pull request by swaager**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Modifications to contributors.md must be checked manually, thanks for your submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 213955f31232f6d6f6e1c1c915d225ff0baa755b

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request needs further work because of the following reason(s):
1. You added/changed/deleted 2 files. You can only add three (3) files `index.html` `main.js` `main.css`.
2. You changed a file at `Games`, this is not allowed, you can only modify `games/swaager`
3. You changed a file called `swaager`, this is not one of the three allowed names.
4. Your `main.js` file was not found, it is a requirement (even if empty)
5. Your `main.css` file was not found, it is a requirement (even if empty)
6. Your `index.html` file was not found, this one should exist and be nonempty

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 03b2a0dfabdb649e14952d7b2e0505fd711c1d6c

**Comment by swaager** [comment]
Added myself and games added

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. You added/changed/deleted 4 files. You can only add three (3) files `index.html` `main.js` `main.css`.
2. You changed a file at `Games`, this is not allowed, you can only modify `games/swaager`
3. Your `main.js` file was not found, it is a requirement (even if empty)
4. Your `main.css` file was not found, it is a requirement (even if empty)

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3a1b08d4419d16e19e4cec75d3275e224426e1a0

**Pull request closed without merging**
